export const SUBMIT_PROFILE_FORM =
  'app/ProfilePage/SUBMIT_PROFILE_FORM';

export const SUBMIT_PROFILE_FORM_SUCCESS =
  'app/ProfilePage/SUBMIT_PROFILE_FORM_SUCCESS';

export const SUBMIT_PROFILE_FORM_ERROR =
  'app/ProfilePage/SUBMIT_PROFILE_FORM_ERROR';
