const FETCH_OFFICES = 'FETCH_OFFICES';
const FETCH_OFFICES_SUCCESS = 'FETCH_OFFICES_SUCCESS';
const FETCH_OFFICES_ERROR = 'FETCH_OFFICES_ERROR';

export {
  FETCH_OFFICES,
  FETCH_OFFICES_SUCCESS,
  FETCH_OFFICES_ERROR
};
