export const SUBMIT_CONTACT_SUPPORT =
  'app/ContactSupport/SUBMIT_CONTACT_SUPPORT';

export const SUBMIT_CONTACT_SUPPORT_SUCCESS =
  'app/ContactSupport/SUBMIT_CONTACT_SUPPORT_SUCCESS';

export const SUBMIT_CONTACT_SUPPORT_ERROR =
  'app/ContactSupport/SUBMIT_CONTACT_SUPPORT_ERROR';
