// TODO: Delete this file once real API is hooked up

export default [
  {
    "id": 18,
    "firstName": "Dr. Johnny",
    "lastName": "Dentist",
    "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/jsa/128.jpg",
    "type": "General Dentist",
    "rating": 7,
    "planStartingCost": 18,
    "affordability": 5,
    "dentistInfo": {
      "officeName": "Johnnys Dentistry",
      "url": "https://example.com",
      "email": "johnnys_dentistry@example.com",
      "phone": "(123) 456-7891",
      "message": "This is a profile message: Nullam gravida, nisl eget dictum mattis, tellus purus posuere diam, at ornare justo felis sit amet ligula. Sed purus turpis, placerat a molestie vel, fermentum nec nisi. Nulla sed nibh non dolor dapibus molestie. In maximus, ligula id lobortis luctus, metus dolor tristique nisl, efficitur scelerisque ante enim malesuada ligula. Ut pellentesque ligula ut enim pellentesque, id posuere sem tincidunt.\n\nEtiam quis cursus mi: sed aliquam rhoncus ex nec fermentum!",
      "address": "993 Tennessee St.",
      "city": "San Francisco",
      "state": "CA",
      "zipCode": "94117",
      "lat": 37.7597686,
      "lng": -122.3889486,
      "createdAt": "2017-03-22T10:22:40.935Z",
      "updatedAt": "2017-03-22T10:22:40.935Z",
    },
  },

  {
    "id": 19,
    "firstName": "Dr. Bill",
    "lastName": "Tooth",
    "avatar": "https://image.freepik.com/free-vector/coloured-doctor-design_1133-26.jpg",
    "type": "General Dentist",
    "rating": 10,
    "planStartingCost": 22,
    "affordability": 4,
    "dentistInfo": {
      "officeName": "Bill Tooth Hurty",
      "url": "https://example.com",
      "email": "bills_dentistry@example.com",
      "phone": "(123) 456-7891",
      "message": "This is a profile message: Nullam gravida, nisl eget dictum mattis, tellus purus posuere diam, at ornare justo felis sit amet ligula. Sed purus turpis, placerat a molestie vel, fermentum nec nisi. Nulla sed nibh non dolor dapibus molestie. In maximus, ligula id lobortis luctus, metus dolor tristique nisl, efficitur scelerisque ante enim malesuada ligula. Ut pellentesque ligula ut enim pellentesque, id posuere sem tincidunt.\n\nEtiam quis cursus mi: sed aliquam rhoncus ex nec fermentum!",
      "address": "69 Clementina St",
      "city": "San Francisco",
      "state": "CA",
      "zipCode": "94117",
      "lat": 37.7864193,
      "lng": -122.3963874,
      "createdAt": "2017-03-22T10:22:40.935Z",
      "updatedAt": "2017-03-22T10:22:40.935Z",
    },
  },

  {
    "id": 13,
    "firstName": "Dr. Sheila",
    "lastName": "Gum",
    "avatar": "https://image.freepik.com/free-vector/doctor-with-stethoscope-design_1133-180.jpg",
    "type": "General Dentist",
    "rating": 8,
    "planStartingCost": 20,
    "affordability": 4,
    "dentistInfo": {
      "officeName": "Gums Dental",
      "url": "https://example.com",
      "email": "gum_dentistry@example.com",
      "phone": "(123) 456-7891",
      "message": "This is a profile message: Nullam gravida, nisl eget dictum mattis, tellus purus posuere diam, at ornare justo felis sit amet ligula. Sed purus turpis, placerat a molestie vel, fermentum nec nisi. Nulla sed nibh non dolor dapibus molestie. In maximus, ligula id lobortis luctus, metus dolor tristique nisl, efficitur scelerisque ante enim malesuada ligula. Ut pellentesque ligula ut enim pellentesque, id posuere sem tincidunt.\n\nEtiam quis cursus mi: sed aliquam rhoncus ex nec fermentum!",
      "address": "550 Guerrero St",
      "city": "San Francisco",
      "state": "CA",
      "zipCode": "94110",
      "lat": 37.7621915,
      "lng": -122.4241652,
      "createdAt": "2017-03-22T10:22:40.935Z",
      "updatedAt": "2017-03-22T10:22:40.935Z",
    },
  },

  {
    "id": 16,
    "firstName": "Dr. Dorothy",
    "lastName": "Root",
    "avatar": "https://image.freepik.com/free-vector/female-doctor_23-2147513552.jpg",
    "type": "Pediatric Dentist",
    "rating": 6,
    "planStartingCost": 26,
    "affordability": 5,
    "dentistInfo": {
      "officeName": "Root Dental",
      "url": "https://example.com",
      "email": "root_dentistry@example.com",
      "phone": "(123) 456-7891",
      "message": "This is a profile message: Nullam gravida, nisl eget dictum mattis, tellus purus posuere diam, at ornare justo felis sit amet ligula. Sed purus turpis, placerat a molestie vel, fermentum nec nisi. Nulla sed nibh non dolor dapibus molestie. In maximus, ligula id lobortis luctus, metus dolor tristique nisl, efficitur scelerisque ante enim malesuada ligula. Ut pellentesque ligula ut enim pellentesque, id posuere sem tincidunt.\n\nEtiam quis cursus mi: sed aliquam rhoncus ex nec fermentum!",
      "address": "1410 Fell St",
      "city": "San Francisco",
      "state": "CA",
      "zipCode": "94117",
      "lat": 37.7736345,
      "lng": -122.4410795,
      "createdAt": "2017-03-22T10:22:40.935Z",
      "updatedAt": "2017-03-22T10:22:40.935Z",
    },
  },
]
