export const CHANGE_PAGE_TITLE = 'App/CHANGE_PAGE_TITLE';

export const FETCH_ACCOUNT_MANAGERS = 'FETCH_ACCOUNT_MANAGERS';
export const FETCH_ACCOUNT_MANAGERS_SUCCESS = 'FETCH_ACCOUNT_MANAGERS_SUCCESS';
export const FETCH_ACCOUNT_MANAGERS_ERROR = 'FETCH_ACCOUNT_MANAGERS_ERROR';

export const SELECT_MANAGER = 'SELECT_MANAGER';

export const TOGGLE_ADDING_MANAGER = 'TOGGLE_ADDING_MANAGER';

export const ADD_MANAGER = 'ADD_MANAGER';
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS';

export const TOGGLE_EDITING_MANAGER = 'TOGGLE_EDITING_MANAGER';
export const EDIT_MANAGER = 'EDIT_MANAGER';
export const EDIT_MANAGER_SUCCESS = 'EDIT_MANAGER_SUCCESS';
