
export const ME_FROM_TOKEN = 'App/ME_FROM_TOKEN';
export const SET_AUTH_DATA = 'App/SET_AUTH_DATA';
export const SET_USER_DATA = 'App/SET_USER_DATA';

export const DENTIST_SPECIALTIES_REQUEST = 'App/DENTIST_SPECIALTIES_REQUEST';
export const DENTIST_SPECIALTIES_SUCCESS = 'App/DENTIST_SPECIALTIES_SUCCESS';
export const DENTIST_SPECIALTIES_ERROR = 'App/DENTIST_SPECIALTIES_ERROR';

export const CHANGE_PAGE_TITLE = 'App/CHANGE_PAGE_TITLE';
