
export const ME_FROM_TOKEN = 'App/ME_FROM_TOKEN';
export const SET_AUTH_STATE = 'App/SET_AUTH_STATE';
export const SET_USER_DATA = 'App/SET_USER_DATA';

export const SERVICES_REQUEST = 'App/SERVICES_REQUEST';
export const SERVICES_REQUEST_SUCCESS = 'App/SERVICES_REQUEST_SUCCESS';
export const SERVICES_REQUEST_ERROR = 'App/SERVICES_REQUEST_ERROR';

export const CHANGE_PAGE_TITLE = 'App/CHANGE_PAGE_TITLE';

export const REVIEW_ADDED = 'App/REVIEW_ADDED';
export const REVIEW_EDITED = 'App/REVIEW_EDITED';

// custom membership plan constants
export const ADD_CUSTOM_MEMBERSHIP = 'App/ADD_CUSTOM_MEMBERSHIP';
export const EDIT_CUSTOM_MEMBERSHIP = 'App/EDIT_CUSTOM_MEMBERSHIP';
export const DELETE_CUSTOM_MEMBERSHIP = 'App/DELETE_CUSTOM_MEMBERSHIP';